config/routes.rb
Blogger::Application.routes.draw do
  root :to => "articles#index"

  resources :authors
  resources :articles
  resources :comments
  resources :tags
  resources :author_sessions

  match 'login'  => 'author_sessions#new',     :as => :login
  match 'logout' => 'author_sessions#destroy', :as => :logout
  
  match ':id'    => 'articles#index'
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list, :image

  has_many :comments
  has_many :taggings
  has_many :tags, :through => :taggings

  validates :title, :presence => true#, :flash => {:validation => "Article can't be blank, fool"}

  has_attached_file :image

  def tag_list
    return self.tags.join(", ")
  end

  def tag_list=(tags_string)
    self.taggings.destroy_all

    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq

    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by_name(tag_name)
      tagging = self.taggings.new
      tagging.tag_id = tag.id
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :except => [:index, :show]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])

    @article.save

    redirect_to article_path(@article), :notice => "@article.title created!"
  end

  def destroy
    @article = Article.find(params[:id])

    @article.destroy

    redirect_to articles_path, :notice => "@article.title deleted!"
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])

    redirect_to article_path(@article), :notice => "@article.title updated!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def d(object)
    debug object if Rails.env == "development"
  end
end

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {:multipart => true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>

  <div>
    <%= flash[:validation] if flash[:validation] %>
  </div>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
   <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <% if @article.image_file_name %>
      <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<h3>Sort by:</h3>
<ul>
	<li><%= link_to "Word count", articles_path(params.merge(:order_by => "word_count"))%></li>
	<li><%= link_to "Title", articles_path(params.merge(:order_by => "title"))%></li>
	<li><%= link_to "Publish Date", articles_path(params.merge(:order_by => "published"))%></li>
</ul>
<hr>
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path, :class => "new_article" %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blogger
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %p.flash
      - flash.each do |key,message|
        = content_tag :p, message, :class => "flash #{key}" unless key == :validation
    #container
      #content
        = yield
        %hr
        %h6
          - if logged_in?
            = "Logged in as #{current_user.username}"
            = link_to "(logout)", logout_path
          - else
            = link_to "(login)", login_path